language: go

go:
  - master

sudo: false

env:
  global:
    - GH_REF: github.com/iocast/iocast.github.io.git
    - secure: aIXkqfPLYW9ljCdNFBakSI+UjmkxjgCEUfjj9K9aQJilrs08Bdef6MOrkh0QjPawgJyTeVX26yylzCfuXeKqgFS9WMVJvDmhCK6eNh7uMJVQDFGHUv+/VwY/qhCLQw1qmdXB2HvyVUEbYplZY+jy2sBU76XSe5L19oL1KlaHcjo=

branches:
  except:
  - master

branches:
  only:
  - develop

install:
  - go get github.com/bmizerany/assert


#after_install:

before_script:
- cd page
- npm install

script:
- hexo generate

#after_script:

after_success:
- cd ..
- chmod a+x ./script/update-gh-pages.sh
- ./script/update-gh-pages.sh
