language: go

go:
  - master

sudo: false

env:
  global:
    - GH_REF: github.com/iocast/iocast.github.io.git
    - secure: Hi/jaJsG2H0wu4ey0LO/5/hblUzCiy97s26FaVNJpEJ20rvzFd4HjMKFeyf8cQGosHecpnWAwVYZOfdvxLtz5gai42aMYTDwTLGtWKepXiYuFwS+F7iy3DAUe/tS07OZBJ4piAOT4YUp86QYMTQRg6Q1N65Ephad/sTz9wLZzRc=

branches:
  except:
  - master

branches:
  only:
  - develop

install:
  - go get -v github.com/spf13/hugo

#after_install:

#before_script:

script:
  - hugo --source page/ --destination ../public/

#after_script:

after_success:
  - chmod a+x ./script/update-gh-pages.sh
  - ./script/update-gh-pages.sh
