name = "Material Design Lite"
license = "Apache 2.0"
licenselink = "https://github.com/iocast/iocast.github.io/blob/develop/page/themes/material-design-lite/LICENSE.md"
description = "Material Design Lite Blog Theme"
homepage = "https://github.com/iocast/iocast.github.io/tree/develop/page/themes/material-design-lite"
tags = ["blog", "material design lite"]
features = ["blog", "material design lite"]
min_version = 0.18.1

[author]
  name = "Iocast"
  homepage = "http://iocast.github.io/"
