BaseUrl= "https://iocast.github.io"
LanguageCode= "en-US"
Title= "think twice code once!"
paginate = 8

Copyright = "All rights reserved © 2018"
canonifyurls = true
theme = "semantic"
newContentEditor = "nano"
sourceRelativeLinksEval = true
#canonifyURLs = true
#relativeURLs = true
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
#pygmentsOptions = "linenos=table"

disqusShortname = "iocast-blog"
#disqus_identifier = ""
#disqus_title = ""
#disqus_url = ""

# like alias
[taxonomies]
  tag = "tags"
  category = "categories"

[[author]]
    name = "James Campbell"

[params]
  SiteDescription = "blog, cheatsheets, best practices, and more"
  DateForm = "Mon, 02 Jan 2006 15:04:05 MST"
  DateFormShort = "Mon, 02 Jan 2006"
  Description = "Welcome to my collection of things I meet in my everyday life."
  Author = "Iocast"
  email = "iocast@me.com"
  PostSummariesFrontPage = 12
  #Ganalytics = "XX-00000000-0"
  #RSSLink = "https://www.jamescampbell.us/index.xml"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  #twitter = "https://www.twitter.com/jamescampbell"
  ShowReadTime = false
  ShowSearch = false

[[params.social]]
  title = "github"
  icon = "github"
  url = "https://github.com/iocast"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = -100
  [[menu.main]]
    name = "Archives"
    url = "/post/"
    weight = -90
  [[menu.main]]
    name = "Cheatsheets"
    url = "/cheatsheet/"
    weight = -80
